services:
  - type: web
    name: retiropay
    env: node
    buildCommand: "cd backend && npm install && npm run build"
    startCommand: "cd backend && npm run start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_6vXUGz7kYbiO@ep-little-dust-ac4158o0-pooler.sa-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
